# Generated by Django 4.1 on 2022-09-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminpanel',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_pass', models.CharField(max_length=200)),
                ('admin_email', models.CharField(max_length=100)),
            ],
        ),
    ]
