# Generated by Django 4.1 on 2022-09-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('cus_id', models.AutoField(primary_key=True, serialize=False)),
                ('cus_name', models.CharField(max_length=100)),
                ('cus_pass', models.CharField(max_length=200)),
                ('cus_email', models.CharField(max_length=100)),
            ],
        ),
    ]
